openapi: '3.0.2'
info:
  title: Argent Bank API
  description: API for managing transactions in Argent Bank
  version: 1.0.0

paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get all transactions for the current month
      description: Returns a list of transactions for the authenticated user
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
      responses:
        '200':
          description: Get transactions successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get a specific transaction
      description: Returns details of a specific transaction
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Transaction ID
      responses:
        '200':
          description: Get transaction details successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update a specific transaction
      description: Updates an existing transaction
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Transaction ID
      requestBody:
        description: Update transaction attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransaction'
      responses:
        '200':
          description: Transaction updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized due to missing or invalid token
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UpdateTransaction:
      type: object
      properties:
        category:
          type: string
          enum:
            - Food
            - Entertainment
            - Transport
            - Utilities
            - Rent
            - Salary
            - Other
        notes:
          type: string
    Transactions:
      type: array
      items:
        $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        id:
          type: string
        accountId:
          type: string
          description: Unique identifier for the bank account
        date:
          type: string
          format: date
        description:
          type: string
        currency:
          type: string
        type:
          type: string
        amount:
          type: number
        category:
          type: string
          enum:
            - Food
            - Entertainment
            - Transport
            - Utilities
            - Rent
            - Salary
            - Other
        notes:
          type: string