import { createSlice } from '@reduxjs/toolkit'

// Initial state of the modal
const initialState = {
  isOpen: false
}

// Redux slice to manage the modal state
const modalSlice = createSlice({
  name: 'modal',
  initialState,
  reducers: {
    // Opens the modal by setting isOpen to true.
    openModal: (state) => {
      state.isOpen = true
    },
    // Closes the modal by setting isOpen to false.
    closeModal: (state) => {
      state.isOpen = false
    }
  }
})

// Actions generated by the modal slice
export const { openModal, closeModal } = modalSlice.actions

export default modalSlice.reducer
